### ISSUE TITLE
Cannot find module "cookie-parser"

### ISSUE THREAD

**Issue by tutnes** [AzureADSamples/WebApp-OpenIdConnect-nodejs#9]
Running npm install and node app.js but I am getting this error:

module.js:327
    throw err;
    ^

Error: Cannot find module 'cookie-parser'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\github\active-directory-node-webapp-openidconnect\app.js:27:20)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)

**Comment by derisen** [comment]
Closing this issue due to inactivity. There is a more recent sample [here](https://github.com/azureadquickstarts/appmodelv2-webapp-openidconnect-nodejs)
